var messages = {
	en_US : {
		language : "Language",
		required : "Required field",
		only_number : "Only number",
		error : "Error",
		yes : "Yes",
		cancel : "Cancel",
		warning : "Warning!",
		deleting : "Deleting",
		surname : "Surname",
		surname_required : "Surname required",
		name : "Name",
		name_required : "Name required",
		country : "Country",
		nationality : "Nationality",
		city : "City",
		address : "Address",
		cap : "Postal code",
		email : "Email address",
		email_required : "Email address required",
		phone : "Phone number",
		date_not_valid : "Not valid date",
		username : "Username",
		username_required : "Username required",
		password : "Password",
		password2 : "Confirm password",
		password_different : "Passwords do not match",
		captcha_value : "Captcha code",
		captcha_required : "Captcha code required",
		confirm_msg : "Are you sure you want to continue?",
		delete_msg : "Are you sure you want to continue?",
		save_msg : "Saving",
		redirect_msg : "Wait, soon you will be redirected ...",
		logout_msg : "Are you sure you want to quit?",
		'datatable' : {
			"sEmptyTable" : "No data found",
			"sInfo" : "Showing _START_ to _END_ of _TOTAL_ entries",
			"sInfoEmpty" : "Showing 0 to 0 of 0 entries",
			"sInfoFiltered" : "(filtered from _MAX_ total entries)",
			"sInfoPostFix" : "",
			"sInfoThousands" : ",",
			"sLengthMenu" : "Show _MENU_ entries",
			"sLoadingRecords" : "Loading...",
			"sProcessing" : "Processing...",
			"sSearch" : "Search:",
			"sZeroRecords" : "No matching records found",
			"oPaginate" : {
				"sFirst" : "First",
				"sLast" : "Last",
				"sNext" : "Next",
				"sPrevious" : "Previous"
			},
			"oAria" : {
				"sSortAscending" : ": activate to sort column ascending",
				"sSortDescending" : ": activate to sort column descending"
			}
		}
		
	},
	it_IT : {
		language : "Lingua",
		required : "Campo obbligatorio",
		only_number : "Solo numeri",
		error : "Errore",
		yes : "Si",
		cancel : "Annulla",
		warning : "Attenzione!",
		deleting : "Eliminazione",
		surname : "Cognome",
		surname_required : "Cognome obbligatorio",
		name : "Nome",
		name_required : "Nome obbligatorio",
		country : "Paese",
		nationality : "Nazionalità",
		city : "comune",
		address : "Indirizzo",
		cap : "Codice postale",
		email : "Email",
		email_required : "Email obbligatoria",
		phone : "Telefono",
		date_not_valid : "Data non valida",
		username : "Username",
		username_required : "Username obbligatorio",
		password : "Password",
		password2 : "Confirma password",
		password_different : "Le password non coincidono",
		captcha_value : "Codice captcha",
		captcha_required : "Captcha obbligatorio",
		confirm_msg : "Sicuro di voler continuare?",
		delete_msg : "Sicuro di voler continuare?",
		save_msg : "Salvataggio",
		redirect_msg : "Attendi, a breve sarai reindirizzato ...",
		logout_msg : "Sicuro di voler uscire?",
		'datatable' : {
			"sEmptyTable" : "Nessun dato",
			"sInfo" : "Mostra _START_ a _END_ di _TOTAL_ righe",
			"sInfoEmpty" : "Mostra 0 a 0 di 0 righe",
			"sInfoFiltered" : "(filtrate da _MAX_ righe totali)",
			"sInfoPostFix" : "",
			"sInfoThousands" : ",",
			"sLengthMenu" : "Mostra _MENU_ righe",
			"sLoadingRecords" : "Caricamento...",
			"sProcessing" : "Processamento...",
			"sSearch" : "Cerca:",
			"sZeroRecords" : "Nessun record trovato",
			"oPaginate" : {
				"sFirst" : "Prima",
				"sLast" : "Ultima",
				"sNext" : "Successiva",
				"sPrevious" : "Precedente"
			},
			"oAria" : {
				"sSortAscending" : ": attiva l'ordinamento per colonna ascendente",
				"sSortDescending" : ": attiva l'ordinamento per colonna discendente"
			}
		}
		
	}
};